version: '2'

networks:
  dev:
    driver: bridge

services:
  fast-data-dev:
    image: landoop/fast-data-dev:2.5.1
    ports:
      - "2181:2181" # ZooKeeper
      - "3030:3030" # UI
      - "8081-8083:8081-8083" # Schema Registry, Kafka REST Proxy, Kafka Connect Distributed
      - "9581-9585:9581-9585" # JMX
      - "9092:9092" # Kafka Broker
    environment:
      ADV_HOST: kubernetes.docker.internal
      SAMPLEDATA: 0
      RUNTESTS: 0
      RUNNING_SAMPLEDATA: 0
    networks:
      - dev

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411" # ZooKeeper
    networks:
      - dev