version: '2'

networks:
  dev:
    driver: bridge

services:
  kafka-stream-demo-app:
    image: kafka-streams-state-store-monitoring-poc:0.0.1-SNAPSHOT
    container_name: kafka-stream-demo-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - fast-data-dev
      - zipkin
    environment:
      spring.profiles.active: dev
      envs.config-server.url: "http://config-server:8888"
      spring.zipkin.base-url: "http://zipkin:9411/"
      spring.kafka.bootstrap-servers: "fast-data-dev:9092"
    networks:
      - dev

  fast-data-dev:
    image: landoop/fast-data-dev:2.5.1
    ports:
      - "2181:2181" # ZooKeeper
      - "3030:3030" # UI
      - "8081-8083:8081-8083" # Schema Registry, Kafka REST Proxy, Kafka Connect Distributed
      - "9581-9585:9581-9585" # JMX
      - "9092:9092" # Kafka Broker
    environment:
      ADV_HOST: fast-data-dev
      SAMPLEDATA: 0
      RUNTESTS: 0
      RUNNING_SAMPLEDATA: 0
    networks:
      - dev

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411" # zipkin ui
    networks:
      - dev